### PR TITLE
Added josephus problem

### PR DESCRIPTION
**Pull request by mahipalimkar**
This PR introduces a recursive solution for the Josephus problem, which determines the safe position in a circle of n people where every k-th person is eliminated until only one person remains.

### CODE REVIEW

**Review by JenilGajjar20 — CHANGES_REQUESTED** [review]
Hey @mahipalimkar, please read the contribution guidelines.

**Comment by mahipalimkar** [comment]
@JenilGajjar20 made changes, please check.

**Review by JenilGajjar20 — CHANGES_REQUESTED** [review]
The file names are not according to the guidelines. Please read the [guidelines](https://github.com/JenilGajjar20/Competitive-Programming_problems/blob/master/CONTRIBUTING.md#adding-solutions) once again.

**Comment by mahipalimkar** [comment]
Hello. Changed file names @JenilGajjar20

**Comment by mahipalimkar** [comment]
@JenilGajjar20 are any other changes required?

**Review by JenilGajjar20 — APPROVED** [review]

**Comment by JenilGajjar20** [comment]
> @JenilGajjar20 are any other changes required?

NO.

**Pull request merged**
