### PR TITLE
added new problem with solution

### PR DESCRIPTION
**Pull request by athu070**
added a problem "Rotate an array by K" with solution file 

this is for hacktoberfest 2023

### CODE REVIEW

**Comment by JenilGajjar20** [comment]
Hey, @athu070. Please go through the guidelines [here](https://github.com/JenilGajjar20/Competitive-Programming_problems/blob/master/CONTRIBUTING.md) and update the **PR** according to it.
It should be **problem.md** file.

**Comment by athu070** [comment]
updated the file name as mentioned in the guidelines to problem.md

**Comment by athu070** [comment]
hey @JenilGajjar20  Can I add some more problems through this branch or should I again fork and create a new branch and then add my new problem?

**Comment by JenilGajjar20** [comment]
Hey, @athu070. You don't have to fork it again. You can either create a new branch or add it via the same branch. But, you know the guidelines for creating a branch, right?

**Pull request merged**
