### PR TITLE
Number guessing challenge Javascript

### PR DESCRIPTION
**Pull request by kanishkasd**
I added the Js folder with html, readme file and also javascript file which contains the related javascript challenge

### CODE REVIEW

**Review by JenilGajjar20 — CHANGES_REQUESTED** [review]
Hey, @kanishkasd. This is **not** the correct format. Read the contribution guidelines given [here](https://github.com/JenilGajjar20/Competitive-Programming_problems/blob/master/CONTRIBUTING.md)

**Comment by kanishkasd** [comment]
I did again this time according to the rules 🤖

**Comment by JenilGajjar20** [comment]
There are no files committed !! @kanishkasd

**Comment by JenilGajjar20** [comment]
There are no files committed in this **PR** !! Should I close this PR?

**Pull request closed without merging**
